services:
  todo-app:
    image: cloudcomputing321/todo-app
    ports:
      - 5000:5000
    depends_on:
      - todo-database
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - MONGO_HOST=todo-database
      - MONGO_PORT=27017
    

  todo-database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db  

volumes:
  mongodb-data:
