apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: flask-app
  name: test-alert-rule
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestAlert
      expr: vector(1)
      labels:
        severity: critical
      annotations:
        summary: "This is a test alert"
        description: "This alert is always firing for testing purposes."
